services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: authservice-app

    ports:
      - "5000:5000"

    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/authservice

      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped


  postgres:
    image: postgres:17-alpine

    container_name: authservice-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authservice

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d authservice"]
      interval: 5s
      timeout: 5s
      retries: 10

    restart: unless-stopped


volumes:
  postgres_data: